### ISSUE TITLE
Regarding Dataset

### ISSUE THREAD

**Issue by rsd2007** [bsridatta/kthfsdv-Perception-Interview#1]
Hi, I am curious regarding how did you collect the dataset? I want to collect more cone images, how can I proceed?
Thanks.

**Comment by bsridatta** [comment]
I used google API to download search results of traffic cones and then removed ones that I didn't match what I wanted. It's a bit time taking obviously. 

Please let me know what your use case is so I can tell you what I would do.

**Comment by rsd2007** [comment]
I am trying to collect different coloured cones in order to perform object detection on it. What do you think how much data will be sufficient?

**Comment by bsridatta** [comment]
If you have the resources you can create a large dataset from Clara or some realistic simulations.
Or set cones in the environment you want and record in different climate
Or prepare some with a green screen and augment the background to synthesize more 
Or if you are a part of a Formula Student team you can join here, contribute, and get access to a ton of data
https://github.com/ddavid/fsoco

I hope this helps, good luck!

**Comment by rsd2007** [comment]
Thanks for the help!
